#!/bin/sh
#
ln -sf {{pkg.path}}/main.js       {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/star.json     {{pkg.svc_var_path}}
# ln -sf {{pkg.path}}/settings.json {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/server        {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/programs      {{pkg.svc_var_path}}
