#!/bin/sh
#
cd {{pkg.svc_var_path}}

echo "###########################################################";
echo "########## Base directory     {{pkg.svc_path}} ";
echo "########## Current directory  {{pkg.svc_var_path}} ";
echo "########## Config directory   {{pkg.svc_config_path}} ";
# echo "########## Mongo connector    ${MONG_CONN} ";
echo "########## Meteor app URL     {{cfg.root_url}} ";
echo "########## Meteor app port    {{cfg.port}} ";
# echo "########## Meteor settings    ${METEOR_SETTINGS} ";
echo "###########################################################";

export MONGO_URL={{cfg.mongo_url}};
export ROOT_URL={{cfg.root_url}};
export PORT={{cfg.port}};

# `exec` makes it so the process that the Habitat supervisor uses is 
# 'node main.js`, rather than the run hook itself.

# `2>&1` makes it so both standard output and standard error go to the standard 
# output stream, so all the logs from the application go to the same place.

exec node main.js 2>&1
